# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Read env variables
    env:
      platform: aws
      region: us-east-1
      account: 123456789012
    # The type of runner that the job will run on

      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Display message"
        run: echo "Hola mundo"

      - name: "Mostrando variables de entorno"
        if: ${{ env.platform == 'aws' }}
        run: |
          echo "Valor de platform: ${{ env.platform }}"
          echo "Valor de region: ${{ env.region }}"
          echo "Valor de account: ${{ env.account }}"

          echo "Valor de secret username: ${{ env.username }}"
          echo "Valor de secret password: ${{ env.password }}"