name: Generando ASCII Art

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Lista de archivos
              run: ls -ltra

            - name: Ejecutando script shell
              run: ./ascii-script.sh

            
