name: Matrix Configuration

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
          matrix:
            sistemas-operativos: [ubuntu-latest, ubuntu-20.04, windows-latest]
            imagenes: [hello-world, alpine]
        runs-on: ${{ matrix.sistemas-operativos }}
        steps:
            - name: Echo Docker Details
              run: docker info

            - name: Run images on ${{ matrix.sistemas-operativos }}
              run: docker run ${{ matrix.imagenes }}